### ISSUE TITLE
Font install not working on Windows 10

### ISSUE THREAD

**Issue by TheGuardianWolf** [lordgiotto/google-font-installer#10]
As stated in the title, the font install does not seem to be working with the cscript process.

I have developed an alternate solution for W7+ that uses PowerShell, although I don't have a W7 machine to test this on.

I have also updated some code and packages to remove security vulnerabilities.

#9

**Comment by lordgiotto** [comment]
Hi TheGuardianWolf, thank you very much for this! I'm deeply sorry for replying so late, I simply didn't notice this before.
I'll have a look into this shortly and I'll try to test in on different windows versions.
Again, thanks for your contribution :)

**Comment by TheGuardianWolf** [comment]
It's okay, I've been using your software + my mods to do font installs since about 2018ish. Great work :P. I just hope that my code is still working. You might want to check on copy-paste as HOPEFULLY the win32 fix is present in the original codebase now.

I've noticed that previously, you install everything sequentially. My modifications also make the install parallel, so it completes very quickly.

**Comment by TheGuardianWolf** [comment]
Also I think line 15 might be a mistake, not sure why I have it outside the if condition. I'm currently busy working on a job so I can review this in the weekends.

**Comment by lordgiotto** [comment]
Probably it can be imported regardless of the os, and then used conditionally.

**Comment by TheGuardianWolf** [comment]
Checked the script, seems to work fine on Linux (WSL) and Win 10.

**Comment by lordgiotto** [comment]
Hi TheGuardianWolf.
Sorry for the huge delay!
I just merged your PR and published the new version on npm.

Thank you very much for your contribution :)

**Comment by TheGuardianWolf** [comment]
No problem :D
