### ISSUE TITLE
Installed in current Directory

### ISSUE THREAD

**Issue by aharris88** [lordgiotto/google-font-installer#2]
I tried it out and it installed the font in the current directory instead of in my fonts directory. I'm on Mac OS X.

**Comment by lordgiotto** [comment]
Hi, thanks for the feedback: have you used `download` or `install` command?
Can you please check if you have the font also in `~/Library/Fonts`?

Thank you :)

**Comment by aharris88** [comment]
I used the `download` command. I used `install` and it worked now. Sorry I didn't read the readme very well.
